CREATE TABLE contactos (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nombre VARCHAR(100) NOT NULL,
 correo VARCHAR(100) NOT NULL,
 telefono VARCHAR(20) NOT NULL,
 fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

